### ISSUE TITLE
Allow I²C 400-kHz Fast-mode (Fm) 

### ISSUE THREAD

**Issue by rei-vilo** [energia/Energia#282]
Allow I²C 400-kHz Fast-mode (Fm)

**Comment by dspdon** [comment]
I realize this Issue is 2+ yrs old ... I'm failing to compile legacy Arduino code that calls Wire.setClock(400000U) to achieve Fm I2C with Energia IDE.  I'm using (trying to use) RBL CC3200 WiFi device.  The branch #343 seems specific to Stellaris, not the CC3200 I'm using (e.g., the Wire lib I just installed doesn't have the setClock definition).

**Comment by rei-vilo** [comment]
If you're using I²C in slave mode, it sets itself automatically to standard mode (100 kHz), fast mode (400 kHz) and fast mode plus (1 MHz).

**Comment by dspdon** [comment]
Right: an I2C slave (e.g., a sensor such an accelerometer) reacts to the clock generated by an I2C master.  But an I2C master (e.g., a CC3200 talking to the sensor) generates the clock and must have that rate explicitly specified if it's not the default.  That's what Wire.setClock(rate) does, and is missing from Energia CC3200 Wire lib.  If you've set 400kHz or higher I2C rates on this platform, let me know how you achieved that.  That would be the code needed to implement setClock...

**Comment by robertinant** [comment]
This issue was moved to energia/tivac-core#36
