### ISSUE TITLE
CC3200: Provide AP example

### ISSUE THREAD

**Issue by rei-vilo** [energia/Energia#414]
Provide an example for the CC3200 access point mode.

- See example at [CreateAPModeWebServer](https://github.com/energia/Energia/tree/master/hardware/cc3200/libraries/WiFi/examples/CreateAPModeWebServer)

**Comment by rei-vilo** [comment]
See [CreateAPModeWebServer](https://github.com/energia/Energia/tree/master/hardware/cc3200/libraries/WiFi/examples/CreateAPModeWebServer)

**Comment by rei-vilo** [comment]
Follow the link in https://github.com/energia/Energia/issues/414#issuecomment-194741431

**Comment by Agam-aviconn** [comment]
Hi all,

I am new to CC3200. I am using Energia as the IDE. I want that my Cc3200 should switch from Access point mode to Station mode.

I want a user to enter network ssid and password in AP mode so that cc3200 can connect to that network in station mode.

How can I do this in Energia.

There is no such example in Energia regarding this.

Kindly provide some guidance.Kindly post the energia code here.

**Comment by rei-vilo** [comment]
@Agam-aviconn 

See [CreateAPModeWebServer](https://github.com/energia/Energia/tree/master/hardware/cc3200/libraries/WiFi/examples/CreateAPModeWebServer)

**Comment by robertinant** [comment]
Please see this thread on TI's e2e: http://e2e.ti.com/support/wireless_connectivity/simplelink_wifi_cc31xx_cc32xx/f/968/p/560192/2051511#2051511
