### ISSUE TITLE
CC3200 SmartConfig Reconnect

### ISSUE THREAD

**Issue by niklasbem** [energia/Energia#534]
Hey guys,

I was experimenting with the WiFi library for the CC3200 for a while, but couldn't find a way reconnect to a network profile that was previously stored via WiFi.startSmartConfig().

Is there a way to do this, in the Adafruit CC3000 library this was possible via WiFi.begin(false, true, DEVICE_NAME).

Thanks for your advice.

**Comment by niklasbem** [comment]
Any updates on that or ideas how to accomplish this function?

**Comment by nachiket-p** [comment]
Yup, SmartConfig is not very useful without this functionality for fully functional app.

**Comment by JordanBelford** [comment]
I'm hitting the same problem. Is there anyway to access the stored wifi profiles on the cc3200? If I knew how to do that I could write some code to try the existing profiles first, and fall back to smartconfig if they all fail or none exist.

**Comment by marcelojunqueira** [comment]
@JordanBelford Looking at texas documentation (http://processors.wiki.ti.com/index.php/Staging:CC3100_%26_CC3200_Protocol)
There is no method to get all the profiles, just to add, delete and get one when you know the SSID

since there is no way to know when you have working profiles, i had to add a config button on my prototype, when i press for 3 secconds it starts the smart config tool, as a backup if i press for 6 secs the AP mode will turn on.

Texas recomend to NOT go to production with just the smart config because it cannot work with all types of network.

@robertinant i have commented 1 line in the WiFi library and know i can reset the board and it uses the Profiles stored:

File: WiFi.CPP
line: 139
 
    //Delete all profiles$
    //
    sl_WlanProfileDel(0xff);

**Comment by robertinant** [comment]
I just committed  change d122937bae6e2c868900cb540f212e5dca3eeeb6 that enhances the WiFi library to be able to reconnect to a previously configured network through SmartConfig.

    - enhance startSmartConfig() to be none blocking.
    - store connection info in a profile after successfull SmartConfig.
    - add begin() without parameter to connect to a stored profile.
    - enhance scanNetworks() to allow reconnecting to the previous AP after a scan.
