### ISSUE TITLE
Sharp_BoosterPackLCD_SPI Freezes on MSP432

### ISSUE THREAD

**Issue by rei-vilo** [energia/Energia#696]
The example Sharp_BoosterPackLCD_SPI for the Sharp Memory Display BoosterPack freezes at the `delay()` function, either the initial `delay(1000);` in `setup()` or the `delay(200);`at the end of `loop()`.

It seems to be related to `OneMsTaskTimer`.

**Comment by rei-vilo** [comment]
Let's use the RTOS `Clock` element from the Galaxia library instead!

See commit 8be91f59b5 on pull-request #697 on branch [issue_696](https://github.com/energia/Energia/tree/issue_696)

**Comment by rei-vilo** [comment]
I've enriched the library with reverse display and orientation selection. 

![image](https://cloud.githubusercontent.com/assets/951776/9211297/695e2092-4081-11e5-971f-87ec244f6854.jpg)

![image](https://cloud.githubusercontent.com/assets/951776/9211310/7871022a-4081-11e5-9075-634cf5557c58.jpg)

**Comment by StefanSch** [comment]
i like the new features - they are really great.
For the timer implementation i have two suggestions:
- Can we use a define which identifies that the compile is running on EMT to switch over to the Galaxia library - this would require that this lib is available for all EMT.
- I also favor the suggestion from Robert to make the decision inside the OneMsTaskTimer. This would make the usage and example easier as this would always be the same.

And finally if this changes would be in the update can go into:
.\libraries\  folder, so that it goes into all Launchpad system.

~ Stefan

**Comment by rei-vilo** [comment]
@StefanSch

I agree with both suggestions. 

> * Can we use a define which identifies that the compile is running on EMT to switch over to the Galaxia library - this would require that this lib is available for all EMT.

A specific `ENERGIA_MT` flag would ease readability and maintenance. See ticket #683 **Create Compilation Variable `ENERGIA_MT`**.

> * I also favor the suggestion from Robert to make the decision inside the OneMsTaskTimer. This would make the usage and example easier as this would always be the same.

Sure! The modification with the use of `Clock` are minimal on the **Sharp_BoosterPackLCD_SPI** file, so they could easily be migrated to **OneMsTaskTimer**.

**Comment by rei-vilo** [comment]
What the quick-and-dirty fix allowed me to do!

![img_1464](https://cloud.githubusercontent.com/assets/951776/9227316/1f22eaac-4113-11e5-8192-ebfa1cc9a7df.jpg)

**Comment by robertinant** [comment]
This has been fixed with commit: 753ea3ce2b8606c1fb796df1e687014569964519
OneMsTaskTimer now uses the SysBios Clock module.
