### ISSUE TITLE
0165E0018 Libraries Multiple Locations and Possible Conflicts

### ISSUE THREAD

**Issue by rei-vilo** [energia/Energia#896]
Energia 0165E0018 has multiple locations for libraries:

* Common folder `/Applications/Energia-18.app/Contents/Java/libraries`
* Specific folders for respective platforms `~/Library/Energia15/packages/energia/hardware/msp432/1.0.15/libraries`, `~/Library/Energia15/packages/energia/hardware/cc3200/1.0.1/libraries` and `~/Library/Energia15/packages/energia/hardware/tivac/1.0.1/libraries`

Some libraries appear twice, as `aJson`, `OneMsTaskTimer`, `PubNub`, once on common folder and once on specific folder, resulting in possible conflicts.

Three questions: 

1. Is there a priority of one folder over the other?
2. How libraries are placed into one or another folder?
3. Should the common folder be kept?

**Comment by robertinant** [comment]
The common folder is where all libraries that have architectures=* in library.properties. All the other library locations have the architectures property set to their respective architecture.

I have eliminated the duplicate libraries so that answers the questions of when what library is picked if there are duplicates. The goal is to eventually have all libraries as common where they support all architectures if possible.
